// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: daily_nutrition.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDailyNutrition = `-- name: CreateDailyNutrition :one
INSERT INTO daily_nutrition_intake(id, created_at, user_id, program, calories, carbohydrates, protein, fat, fiber)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, user_id, program, calories, carbohydrates, protein, fat, fiber
`

type CreateDailyNutritionParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UserID        uuid.UUID
	Program       string
	Calories      float64
	Carbohydrates float64
	Protein       float64
	Fat           float64
	Fiber         float64
}

func (q *Queries) CreateDailyNutrition(ctx context.Context, arg CreateDailyNutritionParams) (DailyNutritionIntake, error) {
	row := q.db.QueryRowContext(ctx, createDailyNutrition,
		arg.ID,
		arg.CreatedAt,
		arg.UserID,
		arg.Program,
		arg.Calories,
		arg.Carbohydrates,
		arg.Protein,
		arg.Fat,
		arg.Fiber,
	)
	var i DailyNutritionIntake
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.Program,
		&i.Calories,
		&i.Carbohydrates,
		&i.Protein,
		&i.Fat,
		&i.Fiber,
	)
	return i, err
}

const deleteDailyNutritionOfUserByUserId = `-- name: DeleteDailyNutritionOfUserByUserId :exec
DELETE FROM daily_nutrition_intake WHERE user_id = $1
`

func (q *Queries) DeleteDailyNutritionOfUserByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDailyNutritionOfUserByUserId, userID)
	return err
}

const deleteRowFromDailyNutritionTableById = `-- name: DeleteRowFromDailyNutritionTableById :exec
DELETE FROM daily_nutrition_intake WHERE id = $1
`

func (q *Queries) DeleteRowFromDailyNutritionTableById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRowFromDailyNutritionTableById, id)
	return err
}

const getDailyNutritionOfUserByUserId = `-- name: GetDailyNutritionOfUserByUserId :many
SELECT id, created_at, user_id, program, calories, carbohydrates, protein, fat, fiber FROM daily_nutrition_intake WHERE user_id = $1
`

func (q *Queries) GetDailyNutritionOfUserByUserId(ctx context.Context, userID uuid.UUID) ([]DailyNutritionIntake, error) {
	rows, err := q.db.QueryContext(ctx, getDailyNutritionOfUserByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyNutritionIntake
	for rows.Next() {
		var i DailyNutritionIntake
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Program,
			&i.Calories,
			&i.Carbohydrates,
			&i.Protein,
			&i.Fat,
			&i.Fiber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
